apiVersion: v1
kind: Service
metadata:
  name: proxy-server-service
  namespace: devopspoc
  labels:
    name: proxy-server-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

  selector:
    name: proxy-server
    deploymentType: BLUE
