apiVersion: v1
kind: Service
metadata:
  name: proxy-server-service
  namespace: default
  labels:
    name: proxy-server-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30007
    targetPort: 8080
    protocol: TCP

  selector:
    name: proxy-server
    deploymentType: GREEN
